

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports shift_in]
set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports reset]
set_property PACKAGE_PIN T1 [get_ports {s[1]}]
set_property PACKAGE_PIN U1 [get_ports {s[0]}]
set_property PACKAGE_PIN W2 [get_ports shift_in]
set_property PACKAGE_PIN T2 [get_ports {D[3]}]
set_property PACKAGE_PIN T3 [get_ports {D[2]}]
set_property PACKAGE_PIN V2 [get_ports {D[1]}]
set_property PACKAGE_PIN W13 [get_ports {D[0]}]
set_property PACKAGE_PIN V19 [get_ports {Q[3]}]
set_property PACKAGE_PIN U19 [get_ports {Q[2]}]
set_property PACKAGE_PIN E19 [get_ports {Q[1]}]
set_property PACKAGE_PIN U16 [get_ports {Q[0]}]


#PART 2 CONSTRAINT FILE FORMATION--------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports {num1[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num1_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num2_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num3_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {num4_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
#set_property PACKAGE_PIN W7 [get_ports {out[6]}]
#set_property PACKAGE_PIN W6 [get_ports {out[5]}]
#set_property PACKAGE_PIN U8 [get_ports {out[4]}]
#set_property PACKAGE_PIN V8 [get_ports {out[3]}]
#set_property PACKAGE_PIN U5 [get_ports {out[2]}]
#set_property PACKAGE_PIN V5 [get_ports {out[1]}]
#set_property PACKAGE_PIN U7 [get_ports {out[0]}]




#set_property PACKAGE_PIN R2 [get_ports {num4[3]}]
#set_property PACKAGE_PIN T1 [get_ports {num4[2]}]
#set_property PACKAGE_PIN U1 [get_ports {num4[1]}]
#set_property PACKAGE_PIN W2 [get_ports {num4[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {segmentActivate[0]}]
#set_property PACKAGE_PIN U2 [get_ports {segmentActivate[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segmentActivate[1]}]
#set_property PACKAGE_PIN U4 [get_ports {segmentActivate[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segmentActivate[2]}]
#set_property PACKAGE_PIN V4 [get_ports {segmentActivate[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segmentActivate[3]}]
#set_property PACKAGE_PIN W4 [get_ports {segmentActivate[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]


#set_property PACKAGE_PIN W5 [get_ports clk]

#set_property PACKAGE_PIN R3 [get_ports {num3[3]}]
#set_property PACKAGE_PIN T2 [get_ports {num3[2]}]
#set_property PACKAGE_PIN T3 [get_ports {num3[1]}]
#set_property PACKAGE_PIN V2 [get_ports {num3[0]}]
#set_property PACKAGE_PIN W13 [get_ports {num2[3]}]
#set_property PACKAGE_PIN W14 [get_ports {num2[2]}]
#set_property PACKAGE_PIN V15 [get_ports {num2[1]}]
#set_property PACKAGE_PIN W15 [get_ports {num2[0]}]
#set_property PACKAGE_PIN W17 [get_ports {num1[3]}]
#set_property PACKAGE_PIN W16 [get_ports {num1[2]}]
#set_property PACKAGE_PIN V16 [get_ports {num1[1]}]
#set_property PACKAGE_PIN V17 [get_ports {num1[0]}]
